Table orders {
    id int [pk]
    color varchar [ref: > paintColor.color]
    interior varchar [ref: > interior.material]
    technology varchar [ref: > technology.package]
    wheels varchar [ref: > wheels.option]
    price int
}

Table paintColor {
    id int [pk]
    color varchar
    price int [ref: < orders.price]
}

Table interior {
    id int [pk]
    material varchar
    price int [ref: < orders.price]
}

Table technology {
    id int [pk]
    package varchar
    price int [ref: < orders.price]
}

Table wheels {
    id int [pk]
    option varchar
    price int [ref: < orders.price]
}