Table orders {
    id int [pk]
    colorId varchar [ref: > paintColors.id]
    interiorId varchar [ref: > interiors.id]
    technologyId varchar [ref: > technologies.id]
    wheelId varchar [ref: > wheels.id]
}

Table paintColors {
    id int [pk]
    color varchar
    price int
}

Table interiors {
    id int [pk]
    material varchar
    price int
}

Table technologies {
    id int [pk]
    package varchar
    price int
}

Table wheels {
    id int [pk]
    option varchar
    price int
}